### ISSUE TITLE
Failing tests (statsd_adapter)

### ISSUE THREAD

**Issue by lukemelia** [ahawkins/harness#6]
```
➜  harness git:(master) rake
Run options: --seed 2535

# Running tests:

..........................................................................................FF

Fabulous tests in 0.227977s, 403.5495 tests/s, 903.5999 assertions/s.

  1) Failure:
test_logging_counter_raises_an_exception_when_not_configured(StatsdAdapterTest) [/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:58]:
[RuntimeError] exception expected, not
Class: <NoMethodError>
Message: <"unmocked method :increment, expected one of [:host, :port]">
---Backtrace---
/Users/lmelia/p/harness/lib/harness/adapters/statsd_adapter.rb:29:in `log_counter'
/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:59:in `block in test_logging_counter_raises_an_exception_when_not_configured'
/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:58:in `test_logging_counter_raises_an_exception_when_not_configured'
---------------

  2) Failure:
test_logging_gauge_raises_an_exception_when_not_configured(StatsdAdapterTest) [/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:42]:
[RuntimeError] exception expected, not
Class: <NoMethodError>
Message: <"unmocked method :gauge, expected one of [:host, :port]">
---Backtrace---
/Users/lmelia/p/harness/lib/harness/adapters/statsd_adapter.rb:24:in `log_gauge'
/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:43:in `block in test_logging_gauge_raises_an_exception_when_not_configured'
/Users/lmelia/p/harness/test/unit/adapters/statsd_adapter_test.rb:42:in `test_logging_gauge_raises_an_exception_when_not_configured'
---------------

92 tests, 206 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/lmelia/p/harness/coverage. 841 / 857 LOC (98.13%) covered.
rake aborted!
Command failed with status (1): [/Users/lmelia/.rvm/rubies/ruby-1.9.2-p180/...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by ahawkins** [comment]
```
adam at mba : ~/projects/harness[master] % rake
/Users/adam/.rvm/gems/ruby-1.9.3-p125-perf/gems/json-1.4.6/lib/json/common.rb:2:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
Run options: --seed 37918

# Running tests:

............................................................................................

Fabulous tests in 0.243303s, 378.1293 tests/s, 846.6809 assertions/s.

92 tests, 206 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/adam/projects/harness/coverage. 841 / 857 LOC (98.13%) covered.
```

Things are working for me. Perhaps it's an issue with your seed value?

**Comment by lukemelia** [comment]
Hmm, what version of webmock are you using? I'm on 1.8.7
